language: generic
# we need super user level permission bcs we make use of docker
sudo: required
services:
  - docker

before_install:
  - docker build -t rifkiadrn/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rifkiadrn/udemy-docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "udemy-docker-react"
  env: "UdemyDockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-501315764306"
  bucket_path: "udemy-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY